server:
  port: 9092
  servlet:
    #jetty
    contextPath: "/api/*"
    #tomcat
    context-path: "/api"

spring:
    profiles:
        active: "@activatedProperties@"
    info:
        build:
            encoding: UTF-8

security-core:
  secret: MiClaveSecretaLocalDefault1234567890123456
  public-paths:
    - /auth/login
